"""Customer email classification with prompt-engineering examples."""

CATEGORIES = "Billing, Technical Support, Feedback, Others"

# Five short sample emails covering the requested categories.
sample_emails = [
	("I was charged twice for my monthly subscription.", "Billing"),
	("The app crashes whenever I upload a photo.", "Technical Support"),
	("Your new dashboard is clear and easy to use.", "Feedback"),
	("What are your store's holiday opening hours?", "Others"),
	("Please explain the late fee on my latest invoice.", "Billing"),
]

new_email = "I cannot reset my password because the link keeps expiring."

# Zero-shot: no labeled examples are supplied.
zero_shot_prompt = f"""Classify the email into exactly one of these categories: {CATEGORIES}.
Return only the category name.

Email: {new_email}
Category:"""

# One-shot: one labeled example demonstrates the task and output format.
one_shot_prompt = f"""Classify the email into exactly one of these categories: {CATEGORIES}.
Return only the category name.

Email: I was charged twice for my monthly subscription.
Category: Billing

Email: {new_email}
Category:"""

# Few-shot: three labeled examples show several category distinctions.
few_shot_prompt = f"""Classify the email into exactly one of these categories: {CATEGORIES}.
Return only the category name.

Email: I was charged twice for my monthly subscription.
Category: Billing

Email: The app crashes whenever I upload a photo.
Category: Technical Support

Email: Your new dashboard is clear and easy to use.
Category: Feedback

Email: {new_email}
Category:"""

print("Five sample emails:")
for email, label in sample_emails:
	print(f"- {email} [{label}]")

print("\nZERO-SHOT PROMPT\n" + zero_shot_prompt)
print("\nONE-SHOT PROMPT\n" + one_shot_prompt)
print("\nFEW-SHOT PROMPT\n" + few_shot_prompt)

# Expected labels are illustrative; prompts are not sent to an LLM here.
expected_category = "Technical Support"
print("\nIllustrative output comparison for the new email:")
print(f"Zero-shot: {expected_category}")
print(f"One-shot:  {expected_category}")
print(f"Few-shot:  {expected_category}")
print(
	"\nEffectiveness: Zero-shot is concise and needs no examples, but can be "
	"less consistent. One-shot clarifies the expected labeling format. Few-shot "
	"shows multiple category boundaries and often improves consistency, at the "
	"cost of a longer prompt. Real model outputs may differ; these outputs are "
	"illustrative rather than generated by an LLM."
)
